# Generated by Django 4.2.21 on 2025-05-13 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zillow_id', models.BigIntegerField(unique=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.CharField(max_length=10)),
                ('bathrooms', models.FloatField(blank=True, null=True)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('home_size', models.IntegerField(blank=True, null=True)),
                ('property_size', models.IntegerField(blank=True, null=True)),
                ('home_type', models.CharField(blank=True, max_length=50, null=True)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('zestimate_amount', models.IntegerField(blank=True, null=True)),
                ('zestimate_last_updated', models.CharField(blank=True, max_length=20, null=True)),
                ('rent_price', models.IntegerField(blank=True, null=True)),
                ('rentzestimate_amount', models.IntegerField(blank=True, null=True)),
                ('rentzestimate_last_updated', models.CharField(blank=True, max_length=20, null=True)),
                ('tax_value', models.FloatField(blank=True, null=True)),
                ('tax_year', models.IntegerField(blank=True, null=True)),
                ('last_sold_date', models.CharField(blank=True, max_length=20, null=True)),
                ('last_sold_price', models.IntegerField(blank=True, null=True)),
                ('link', models.URLField()),
            ],
        ),
    ]
